name: riilfit
description: A new Flutter project.

publish_to: "none" # Do not remove this line

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_native_splash: ^2.2.13
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  firebase_core: ^2.1.0
  flutterwave_standard: 1.0.7
  firebase_database: ^10.0.3
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  
  get: ^4.6.5
  get_storage: ^2.0.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  overlay_support: ^2.0.1
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  pin_code_fields: ^7.4.0
  http: ^0.13.5
  shared_preferences:
  jwt_decoder:
  firebase_storage: ^11.1.0
  image_picker: ^0.8.6
  qr_flutter: ^4.0.0
  google_fonts: ^4.0.4
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.1
  intl: ^0.18.0
  form_builder_validators: ^9.0.0
  shimmer: ^3.0.0
  mono_flutter: ^1.1.3
dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: null
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/certificates/
    - assets/icons/
    - assets/animations/
    - assets/rive_assets/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf  
