name: riilfit
description: A new Flutter project.

publish_to: "none" # Do not remove this line

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_storage: ^2.0.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  overlay_support: ^2.0.1
  path_provider: ^2.0.11
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.13
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
